### ISSUE TITLE
Benefits upgrading to Duex5 and individual motor drivers?

### ISSUE THREAD

**Issue by eMPai-git** [fxstein/Modix3D#1]
Hello @fxstein,

may I kindly ask:
What are the benefits of upgrading to Duex5 and individual motor drivers?

We also thought about the Duex5 expansion board for our Big60 v3.

**Comment by fxstein** [comment]
Hi,

Found many benefits for the upgrade. Listing a few top of mind:

Higher sustained speeds due to precision control of every motor. Able to print at up to 150mm/s and move at up to 300mm/s - making prints at lower speeds more reliable and precise. 

Better stall detection - really impossible when 2 or more motors are combined 

Higher acceleration and jerk settings

Extra ports to control a variety of things like heated bed (bypassing the static controller) now bed temperature is part of the gcode file. But also control for dimmable LEDs.  

Made the V3 so much more capable. Happy to share more details as well as a case/housing design to print that fits on the back of the printer. 

Only real effort was the re-cabeling one has to do. Bought the same cables and connectors and handmade the new individual motor cables. A few hours of work - but totally worth it in my opinion. 

Hope this helps!

**Comment by fxstein** [comment]
Oh and totally forgot:

Auto bed leveling. Controlling the bed with 4 individual motors makes that possible. So much more precise than the manual bed leveling. 
And because it's automatic it happens before every print.

**Comment by eMPai-git** [comment]
Thanks for your answer.
I was hoping to get higher acceleration and jerk settings. The Big60 v3 seems like a capable machine, limited by its electronics.
The heated bed control is something I thought about, too. Great to hear that it is possible.
The auto bed leveling sounds like the icing on the cake.

Hopefully I'll find the time to do the upgrade.

I'm closing this issue because it is solved. :+1:
